#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-PackageHomePage: https://github.com/paxx12-snapmaker-u1/SnapmakerU1-Extended-Firmware
# SPDX-FileCopyrightText: Copyright (c) 2026 @paxx12

EXTENDED_CFG="/home/lava/printer_data/config/extended/extended2.cfg"
EXPORTER_ADDRESS=$(/usr/local/bin/extended-config.py get "$EXTENDED_CFG" monitoring klipper_exporter "")

NAME="prometheus-klipper-exporter"
DAEMON="/usr/local/bin/prometheus-klipper-exporter"
PIDFILE="/var/run/$NAME.pid"

start() {
    if [ -z "$EXPORTER_ADDRESS" ]; then
        echo "prometheus-klipper-exporter is disabled in extended2.cfg, not starting."
        return
    fi

    echo "Starting $NAME: "
    if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE") 2>/dev/null; then
        echo "already running"
        return 1
    fi

    . /usr/local/sbin/limits-helper.sh
    limits_enter monitoring 32M

	start-stop-daemon -S -m -q -b -c lava -p "$PIDFILE" -x $DAEMON -- -web.listen-address "$EXPORTER_ADDRESS"
    echo "OK"
}

stop() {
    echo "Stopping $NAME: "
    if [ -f "$PIDFILE" ]; then
        start-stop-daemon -K -p "$PIDFILE" -s TERM
        rm -f "$PIDFILE"
        echo "OK"
    else
        echo "not running"
    fi
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit $?
