#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-PackageHomePage: https://github.com/paxx12-snapmaker-u1/SnapmakerU1-Extended-Firmware
# SPDX-FileCopyrightText: Copyright (c) 2026 @paxx12

OCTOEVERYWHERE_DAEMON="/usr/local/sbin/octoeverywhered"
OCTOEVERYWHERE_PIDFILE="/var/run/octoeverywhere.pid"
OCTOEVERYWHERE_LOGFILE="/home/lava/printer_data/logs/octoeverywhere.log"
OCTOEVERYWHERE_STATE_DIR="/home/lava/printer_data/octoeverywhere-store"

# Load config from user
EXTENDED_CFG="/home/lava/printer_data/config/extended/extended2.cfg"
CLOUD_PROVIDER=$(/usr/local/bin/extended-config.py get "$EXTENDED_CFG" remote_access cloud none)

start_octoeverywhere() {
    if [ -f "$OCTOEVERYWHERE_PIDFILE" ] && kill -0 "$(cat "$OCTOEVERYWHERE_PIDFILE")" 2>/dev/null; then
        echo "moonraker_octoeverywhere already running"
        return 0
    fi

    . /usr/local/sbin/limits-helper.sh
    limits_enter octoeverywhere 80M

    printf "Starting moonraker_octoeverywhere: "
    mkdir -p "$OCTOEVERYWHERE_STATE_DIR"
    mv "$OCTOEVERYWHERE_LOGFILE" "$OCTOEVERYWHERE_LOGFILE.old"

    start-stop-daemon -S -b -m -u lava \
        -p "$OCTOEVERYWHERE_PIDFILE" \
        -x "$OCTOEVERYWHERE_DAEMON"

    echo "OK"
}

start() {
    case "$CLOUD_PROVIDER" in
        octoeverywhere)
            start_octoeverywhere
            ;;
        *)
            echo "No cloud is enabled in the extended configuration, not starting any cloud service."
            exit 0
            ;;
    esac
}

stop() {
    # Stop all cloud services, if any are running.
    printf "Stopping OctoEverywhere: "
    if [ -f "$OCTOEVERYWHERE_PIDFILE" ]; then
        start-stop-daemon -K -p "$OCTOEVERYWHERE_PIDFILE" -s TERM
        rm -f "$OCTOEVERYWHERE_PIDFILE"
        echo "OK"
    else
        echo "not running"
    fi
}

case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart|reload)
        stop
        sleep 1
        start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit $?
